[package]
name = "emmylua_ls"
version = "0.1.0"
edition = "2021"

[dependencies]
lsp-server = "0.7.7"
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7"
dirs = "5"

code_analysis = { path = "../code_analysis" }
serde.workspace = true
serde_json.workspace = true
lsp-types.workspace = true
log.workspace = true
fern.workspace = true
chrono.workspace = true
notify.workspace = true