name: Upload Crates

on:
  push:
    tags:
      - '*'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Set version
        run: |
          echo "current ref ${{ github.ref }}"
          cargo run -p edit_version -- ${{ github.ref }}
      - name: Publish
        run: |
          cd crates/emmylua_code_analysis
          cargo publish --allow-dirty
          cd ../emmylua_ls
          cargo publish --allow-dirty
          cd ../emmylua_doc_cli
          cargo publish --allow-dirty
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
